/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + import sanity
         * @description Return a coarse health snapshot.
         *
         *     Imports the load-bearing internal modules so a broken deploy
         *     (missing dep, broken import path, syntax error in a transitive)
         *     surfaces at ``/health`` instead of at the first real call.
         *     The imports are intentionally re-done per call rather than at
         *     module load — that way a hot patch + reload doesn't need a
         *     process restart to be visible here.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score an explicit portfolio without touching Supabase
         * @description Compute deterministic 0-1000 score + 3 dimension scores + the
         *     raw risk metrics for the supplied holdings.
         *
         *     Deliberately stateless: no Supabase reads, no LLM calls, no
         *     cookie / JWT requirement. Same Pydantic + engine path used by
         *     the Streamlit Copilot page; the math is shared.
         */
        post: operations["score_portfolio_endpoint_api_v1_risk_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/score_from_active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score the authed user's active portfolio using real market data
         * @description Compute the deterministic 0..1000 score for the caller's active
         *     portfolio, using real adjusted-close prices pulled (and cached)
         *     via the backend market-data service.
         *
         *     Resolution order for "active portfolio":
         *       1. The default portfolio flagged in Supabase (``is_default=true``).
         *       2. The most-recent portfolio if no default is set.
         *       3. Empty → 422 ``no_active_portfolio``.
         *
         *     Why not also let the caller pass a ``portfolio_id``? Phase 4 keeps
         *     the contract minimal — the UI shows one card per portfolio with a
         *     "Set as default" toggle. When a richer UI lands, we add an
         *     explicit ``portfolio_id`` field.
         */
        post: operations["score_from_active_endpoint_api_v1_risk_score_from_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/last_snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The prior-day portfolio snapshot, for the 'what changed' delta
         * @description Return the most recent snapshot older than ~a day (the baseline the
         *     dashboard diffs today's score against), or null when there isn't one.
         */
        get: operations["last_snapshot_endpoint_api_v1_risk_last_snapshot_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/snapshot_history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent portfolio snapshots (score/vol/VaR over time) for trend lines
         * @description Recent snapshots oldest→newest so the score/risk pages can draw trend
         *     sparklines. Fail-soft to an empty list.
         */
        get: operations["snapshot_history_endpoint_api_v1_risk_snapshot_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/report_from_active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Full risk report for the authed user's active portfolio
         * @description Build the full ``RiskReport`` (VaR/CVaR, factor betas, stress
         *     test, component VaR, liquidity) using real adjusted-close prices
         *     via the same cached service ``/risk/score_from_active`` uses.
         *
         *     Heavier than /score_from_active (Monte Carlo + factor regressions
         *     against SPY/QQQ/GLD/TLT/IWM/VTV — fetches their history too). The
         *     file-cached market_data layer absorbs the cold-cache latency.
         */
        post: operations["report_from_active_endpoint_api_v1_risk_report_from_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/efficient_frontier": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Efficient frontier + the active portfolio's risk/return point */
        post: operations["efficient_frontier_endpoint_api_v1_risk_efficient_frontier_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Project portfolio P&L across a −30%…+30% market move sweep */
        post: operations["scenarios_endpoint_api_v1_risk_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Structured AI risk diagnosis over already-computed metrics */
        post: operations["explain_endpoint_api_v1_risk_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Reference annualized stats: S&P 500 + 60/40 */
        get: operations["benchmarks_endpoint_api_v1_risk_benchmarks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/historical_scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay real market crises on the active portfolio
         * @description What the caller's ACTUAL holdings would have done through COVID / 2022 /
         *     2018Q4 / GFC — realised return, drawdown, S&P 500 over the same window, and
         *     recovery time. Deterministic, no credits.
         */
        post: operations["historical_scenarios_endpoint_api_v1_risk_historical_scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/var_backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backtest the portfolio's 1-day VaR vs realised breaches
         * @description Gaussian 1-day VaR vs how often the realised daily loss actually breached
         *     it over the trailing window, plus the empirical return distribution.
         *     Deterministic, no credits.
         */
        post: operations["var_backtest_endpoint_api_v1_risk_var_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the authed user's portfolios
         * @description Authed-only. Returns the JWT holder's RLS-filtered portfolios.
         */
        get: operations["list_my_portfolios_api_v1_portfolios_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new portfolio owned by the caller
         * @description Insert a new row. Supabase RLS pins `user_id` to the caller via
         *     the `DEFAULT auth.uid()` clause on the column — we never send it
         *     explicitly, so a buggy client can't impersonate.
         */
        post: operations["create_portfolio_endpoint_api_v1_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one portfolio owned by the caller
         * @description Hard delete. RLS prevents touching rows the caller doesn't own.
         */
        delete: operations["delete_portfolio_endpoint_api_v1_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update one or more fields on a portfolio
         * @description Patch fields. Only fields explicitly set in the request body are
         *     applied; omitted fields keep their existing DB values.
         */
        patch: operations["update_portfolio_endpoint_api_v1_portfolios__portfolio_id__patch"];
        trace?: never;
    };
    "/api/v1/market/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest adjusted close per ticker
         * @description Return the most recent adjusted close + bar date per ticker.
         *
         *     Tickers yfinance can't price (delisted, typo) are silently
         *     omitted from `prices`; compare against `requested` to find them.
         */
        get: operations["get_prices_api_v1_market_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/market/sentiment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * AI sentiment per holding (authed, credits)
         * @description Per-holding AI sentiment over recent headlines for the caller's ACTIVE
         *     portfolio. Credit-gated (it's an LLM call per ticker); fail-open on a
         *     metering blip; degrades to neutral/data-only without an LLM key, so it never
         *     500s. Cached per ticker-set in the service.
         */
        post: operations["portfolio_sentiment_api_v1_market_sentiment_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Last N days of one or more FRED series
         * @description Return latest-value + trailing window for each allow-listed series.
         */
        get: operations["get_series_api_v1_macro_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/yield_curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest US Treasury daily yield curve
         * @description Return today's (or the most recent published) Treasury curve.
         */
        get: operations["get_yield_curve_api_v1_macro_yield_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/regime": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market-regime snapshot: VIX, Fear & Greed, yield curve
         * @description Return the current market regime. Public.
         *
         *     Each leg (VIX / Fear & Greed / yield-curve status) is fetched
         *     independently and nulls itself on upstream failure — the panel
         *     renders partially rather than 500-ing on one dead source. Hence no
         *     error branch here: a well-formed (possibly partially-null) snapshot
         *     is always a 200.
         */
        get: operations["get_regime_api_v1_macro_regime_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/regime_detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Market-wide regime (bull/bear/transition) + history
         * @description Return the composite market regime (bull / bear / transition) with a
         *     confidence, the sub-signals, and a ~1y history. Public. Fails soft to an
         *     empty snapshot — always a 200, never blocks the /markets page.
         */
        get: operations["get_regime_detail_endpoint_api_v1_macro_regime_detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/movers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sector performance + today's top gainers/losers
         * @description Sector ETF performance + S&P-500 top gainers/losers/unusual-volume.
         *     Public, free (yfinance). Fail-soft: any leg may be empty if its upstream is
         *     down — always a 200, never blocks the /markets page.
         */
        get: operations["get_movers_endpoint_api_v1_macro_movers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/news": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest source-labeled macro market news
         * @description Aggregated macro headlines. Public, free, fail-soft to an empty list.
         */
        get: operations["get_news_endpoint_api_v1_macro_news_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Plan + subscription snapshot for the caller
         * @description Return the authed user's current plan, their Stripe
         *     subscription row (if any), and the plan catalogue for rendering
         *     the pricing table without a second round-trip.
         */
        get: operations["billing_me_api_v1_billing_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/admin/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Owner-only: aggregate token/cost/credit usage
         * @description Month-to-date usage aggregates (tokens / $ / credits, per kind + per
         *     user) for the owner dashboard. 403 for everyone else.
         */
        get: operations["billing_admin_usage_api_v1_billing_admin_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Owner-only: live in-process API call metrics
         * @description Real-time, in-process counters for the owner live-activity view: per-route
         *     HTTP volume/latency/errors + per external-provider (yfinance/FMP/Massive/
         *     FRED/Treasury) call outcomes. Pure memory read — no DB hit — so it's safe to
         *     poll every few seconds. Counters are monotonic since process start (reset on
         *     deploy); the dashboard diffs consecutive snapshots to show live rates. The
         *     billing ledger ($/credits) stays in /admin/usage. 403 for non-owners.
         */
        get: operations["billing_admin_metrics_api_v1_billing_admin_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/admin/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Owner-only: integration config + live checks
         * @description Integration config presence (instant) + optional live key-validation
         *     checks (``?live=true``). Owner only (403 otherwise). Never returns secret
         *     values — only present/missing + state.
         */
        get: operations["billing_admin_status_api_v1_billing_admin_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/checkout_session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Stripe Checkout session for a paid plan
         * @description Returns the one-time hosted Checkout URL. The frontend redirects
         *     to it; Stripe's hosted page handles card capture + 3DS + webhook
         *     fire-back into our Supabase project.
         *
         *     The user's ``user.id`` is set as ``client_reference_id`` on the
         *     Stripe session so the webhook can correlate Stripe customer → our
         *     auth user when the subscription is created.
         */
        post: operations["create_checkout_session_endpoint_api_v1_billing_checkout_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/portal_session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Stripe Customer Portal session
         * @description Returns a one-time URL into Stripe's hosted Customer Portal
         *     (card management, plan switch, cancel, invoices). The customer ID
         *     is resolved from the user's subscription row — clients do NOT
         *     pass it.
         *
         *     422 when the user has never had a subscription (free-tier user who
         *     wandered onto Settings before subscribing). The frontend should
         *     redirect them to /pricing instead.
         */
        post: operations["create_portal_session_endpoint_api_v1_billing_portal_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Chat with the AI Portfolio Copilot about the active portfolio
         * @description Answer a chat turn about the caller's active portfolio.
         *
         *     Flow:
         *       1. Resolve positions + score (422 codes on empty/unpriceable data).
         *       2. Gate on the user's monthly chat quota (429 when exhausted;
         *          fail-OPEN on a Supabase blip — availability over strict metering).
         *       3. Dispatch to the orchestrator with the LLM callable (or ``None``
         *          → deterministic templates).
         */
        post: operations["copilot_chat_endpoint_api_v1_copilot_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copilot 2.0 — intent-routed, evidence-grounded answer
         * @description Copilot 2.0: classify the message into one of 8 intents, gather
         *     deterministic evidence (ticker FactPacks, portfolio score, macro regime,
         *     fee/tax scans, metric glossary), then synthesize ONE answer in the fixed
         *     five-section format using only that evidence.
         *
         *     Unlike ``/chat`` this does NOT require an active portfolio — ticker /
         *     compare / macro / explain intents answer with no holdings. Evidence
         *     gathering is fail-soft (a dead provider just thins the evidence).
         *     Credit-gated (LLM); fail-open on a metering blip; data-only without a key.
         */
        post: operations["copilot_ask_endpoint_api_v1_copilot_ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/copilot/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Streaming (SSE) Copilot chat — answer tokens arrive as written
         * @description Same as /chat but **streams** the answer over Server-Sent Events so
         *     the UI renders text as it's generated instead of waiting for the whole
         *     turn. Events: ``status`` (phase), ``delta`` ({text}), ``done``
         *     ({agent_name, grounded_in, risk_levers}), ``error`` ({code, message}).
         *
         *     Auth is enforced up-front (a 401 here is a normal HTTP error, not an SSE
         *     frame). Everything after the stream starts is reported via SSE events —
         *     a 422 (no portfolio) / 429 (quota) becomes an ``error`` event so the
         *     client maps it to the same friendly CTA as the non-streaming route.
         */
        post: operations["copilot_chat_stream_endpoint_api_v1_copilot_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/backtest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Backtest the authed user's active portfolio
         * @description Run the requested strategy over the active portfolio and return the
         *     equity curve, drawdown series, scalar stats, and benchmark total
         *     return. See ``services.quant_backtest`` for the math + error codes.
         */
        post: operations["backtest_active_endpoint_api_v1_quant_backtest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/quant/attribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Performance attribution (Brinson + factor) for the active portfolio
         * @description Brinson sector decomposition + multi-factor regression + tracking-error
         *     / information-ratio / hit-ratio for the caller's active portfolio vs SPY.
         *     Deterministic (no LLM, no credits).
         */
        post: operations["attribution_active_endpoint_api_v1_quant_attribution_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/fact_pack/{ticker}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compact, source-attributed FactPack for a ticker (no credit) */
        get: operations["fact_pack_api_v1_research_fact_pack__ticker__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/research/verdict": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** LLM verdict over a FactPack (credit-gated) */
        post: operations["verdict_api_v1_research_verdict_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/institutions/smart_money": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Institutional conviction for your holdings */
        get: operations["smart_money_api_v1_institutions_smart_money_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/institutions/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Top ~30 institutional 13F filers */
        get: operations["top_api_v1_institutions_top_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/institutions/{cik}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** A fund's top holdings + QoQ changes */
        get: operations["detail_api_v1_institutions__cik__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit beta feedback */
        post: operations["submit_feedback_api_v1_feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalystBlock */
        AnalystBlock: {
            /** Rating */
            rating?: string | null;
            /** Num Analysts */
            num_analysts?: number | null;
            /** Target Low */
            target_low?: number | null;
            /** Target Consensus */
            target_consensus?: number | null;
            /** Target High */
            target_high?: number | null;
            /** Implied Upside Pct */
            implied_upside_pct?: number | null;
        };
        /**
         * BacktestRequest
         * @description Inbound body. The active portfolio supplies the tickers; the body
         *     only chooses the strategy + window + tuning knobs.
         *
         *     ``lookback`` / ``top_n`` are momentum-only and ignored by the other
         *     two strategies (kept on the shared body so the frontend posts one
         *     shape regardless of strategy).
         */
        BacktestRequest: {
            /**
             * Strategy
             * @default static
             * @enum {string}
             */
            strategy?: "static" | "equal_weight" | "momentum";
            /**
             * Years
             * @default 3
             */
            years?: number;
            /**
             * Rebalance Freq
             * @default M
             * @enum {string}
             */
            rebalance_freq?: "D" | "W" | "M" | "Q";
            /**
             * Benchmark
             * @default SPY
             */
            benchmark?: string;
            /**
             * Lookback
             * @default 252
             */
            lookback?: number;
            /**
             * Top N
             * @default 5
             */
            top_n?: number;
        };
        /**
         * ChatRequest
         * @description One chat turn from the user. The orchestrator routes the message
         *     to the right agent (analyzer / optimizer); we don't parse intent
         *     here.
         */
        ChatRequest: {
            /** Message */
            message: string;
        };
        /**
         * CheckoutSessionRequest
         * @description Body for ``POST /api/v1/billing/checkout_session``.
         */
        CheckoutSessionRequest: {
            /**
             * Plan
             * @enum {string}
             */
            plan: "basic" | "pro";
            /** Success Path */
            success_path?: string | null;
            /** Cancel Path */
            cancel_path?: string | null;
        };
        /** CopilotAskRequest */
        CopilotAskRequest: {
            /** Message */
            message: string;
        };
        /** DataQuality */
        DataQuality: {
            /**
             * Coverage
             * @default 0
             */
            coverage?: number;
            /** Sources */
            sources?: components["schemas"]["SourceRef"][];
            /** Warnings */
            warnings?: string[];
        };
        /** ExplainContributor */
        ExplainContributor: {
            /** Ticker */
            ticker: string;
            /** Pct */
            pct: number;
        };
        /** ExplainDimension */
        ExplainDimension: {
            /**
             * Name
             * @default
             */
            name?: string;
            /** Score */
            score?: number | null;
            /**
             * Status
             * @default
             */
            status?: string;
        };
        /** ExplainLiquidity */
        ExplainLiquidity: {
            /** Ticker */
            ticker: string;
            /** Days To Liquidate */
            days_to_liquidate?: number | null;
        };
        /** ExplainMetrics */
        ExplainMetrics: {
            /** Annual Return */
            annual_return?: number | null;
            /** Annual Volatility */
            annual_volatility?: number | null;
            /** Sharpe Ratio */
            sharpe_ratio?: number | null;
            /** Max Drawdown */
            max_drawdown?: number | null;
            /** Var 95 Daily */
            var_95_daily?: number | null;
            /** Cvar 95 Daily */
            cvar_95_daily?: number | null;
            /** Beta To Benchmark */
            beta_to_benchmark?: number | null;
            /** Total Value */
            total_value?: number | null;
            /** Cash Weight */
            cash_weight?: number | null;
        };
        /** ExplainSnapshotDelta */
        ExplainSnapshotDelta: {
            /** As Of */
            as_of?: string | null;
            /** Prev Overall Score */
            prev_overall_score?: number | null;
            /** Prev Annual Volatility */
            prev_annual_volatility?: number | null;
            /** Prev Sharpe Ratio */
            prev_sharpe_ratio?: number | null;
        };
        /**
         * FactPack
         * @description The compact, source-attributed fact sheet for one ticker.
         */
        FactPack: {
            /** Ticker */
            ticker: string;
            /** Name */
            name?: string | null;
            /** Sector */
            sector?: string | null;
            /** Industry */
            industry?: string | null;
            /**
             * Currency
             * @default USD
             */
            currency?: string;
            /** As Of */
            as_of?: string | null;
            /** Price */
            price?: number | null;
            /** Market Cap */
            market_cap?: number | null;
            /** Beta */
            beta?: number | null;
            valuation?: components["schemas"]["ValuationBlock"];
            quality?: components["schemas"]["QualityBlock"];
            growth?: components["schemas"]["GrowthBlock"];
            analyst?: components["schemas"]["AnalystBlock"];
            /** Peers */
            peers?: components["schemas"]["PeerCompareRow"][];
            /** News */
            news?: components["schemas"]["NewsHeadline"][];
            /** Drivers */
            drivers?: string[];
            /** Risk Flags */
            risk_flags?: string[];
            data_quality?: components["schemas"]["DataQuality"];
        };
        /** FeedbackIn */
        FeedbackIn: {
            /** Message */
            message: string;
            /**
             * Context
             * @default
             */
            context?: string;
        };
        /** GrowthBlock */
        GrowthBlock: {
            /** Revenue Cagr */
            revenue_cagr?: number | null;
            /** Eps Cagr */
            eps_cagr?: number | null;
            /** Revenue Growth Yoy */
            revenue_growth_yoy?: number | null;
            /** Earnings Growth Yoy */
            earnings_growth_yoy?: number | null;
            /**
             * Periods
             * @default 0
             */
            periods?: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoldingIn
         * @description One row in the request body. Maps 1:1 to
         *     ``domain.models.AssetPositionInput`` minus a couple of nullable
         *     quality-of-life fields. Same validation rules apply once we
         *     rebuild the engine's model — keeping the schema deliberately
         *     permissive here lets the engine emit the precise error code.
         */
        HoldingIn: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @default
             */
            name?: string;
            /**
             * Asset Type
             * @default public_security
             * @enum {string}
             */
            asset_type?: "public_security" | "cash" | "crypto" | "real_estate";
            /** Market Value */
            market_value: number;
            /** Cost Basis */
            cost_basis?: number | null;
            /**
             * Expense Ratio
             * @default 0
             */
            expense_ratio?: number;
            /**
             * Source
             * @default api
             */
            source?: string;
            /** Proxy Ticker */
            proxy_ticker?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled?: boolean;
        };
        /**
         * HoldingValue
         * @description One ticker's persisted record on a portfolio row.
         */
        HoldingValue: {
            /** Shares */
            shares: number;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Sector */
            sector?: string | null;
            /** Asset Type */
            asset_type?: string | null;
            /** Account */
            account?: string | null;
            /** Currency */
            currency?: string | null;
            /** Margin Eligible */
            margin_eligible?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * NewsHeadline
         * @description Metadata ONLY — title/site/published/url. No article body is ever
         *     forwarded to the LLM (principle: no raw blobs).
         */
        NewsHeadline: {
            /** Title */
            title: string;
            /** Site */
            site?: string | null;
            /** Published */
            published?: string | null;
            /** Url */
            url?: string | null;
        };
        /** PeerCompareRow */
        PeerCompareRow: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @default
             */
            name?: string;
            /** Market Cap */
            market_cap?: number | null;
            /** Pe */
            pe?: number | null;
            /** Ps */
            ps?: number | null;
            /** Net Margin */
            net_margin?: number | null;
            /** Roe */
            roe?: number | null;
        };
        /**
         * PortalSessionRequest
         * @description Body for ``POST /api/v1/billing/portal_session``.
         */
        PortalSessionRequest: {
            /** Return Path */
            return_path?: string | null;
        };
        /**
         * PortfolioCreateRequest
         * @description Body for ``POST /api/v1/portfolios``.
         */
        PortfolioCreateRequest: {
            /** Name */
            name: string;
            /** Holdings */
            holdings?: {
                [key: string]: components["schemas"]["HoldingValue"];
            };
            /**
             * Margin Loan
             * @default 0
             */
            margin_loan?: number;
            /**
             * Contributed Capital
             * @default 0
             */
            contributed_capital?: number;
            /**
             * Cash Balance
             * @default 0
             */
            cash_balance?: number;
            /**
             * Is Default
             * @default false
             */
            is_default?: boolean;
        };
        /**
         * PortfolioPatchRequest
         * @description Body for ``PATCH /api/v1/portfolios/{id}``.
         *
         *     Every field is optional — the route only applies fields the caller
         *     explicitly set so a small UI edit doesn't accidentally null other
         *     columns.
         */
        PortfolioPatchRequest: {
            /** Name */
            name?: string | null;
            /** Holdings */
            holdings?: {
                [key: string]: components["schemas"]["HoldingValue"];
            } | null;
            /** Margin Loan */
            margin_loan?: number | null;
            /** Contributed Capital */
            contributed_capital?: number | null;
            /** Cash Balance */
            cash_balance?: number | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /** QualityBlock */
        QualityBlock: {
            /** Gross Margin */
            gross_margin?: number | null;
            /** Operating Margin */
            operating_margin?: number | null;
            /** Net Margin */
            net_margin?: number | null;
            /** Roe */
            roe?: number | null;
            /** Roa */
            roa?: number | null;
            /** Roic */
            roic?: number | null;
            /** Current Ratio */
            current_ratio?: number | null;
            /** Debt To Equity */
            debt_to_equity?: number | null;
            /** Interest Coverage */
            interest_coverage?: number | null;
        };
        /**
         * ReportFromActiveRequest
         * @description Body for ``POST /api/v1/risk/report_from_active``.
         *
         *     Matches ScoreFromActiveRequest — both endpoints resolve the active
         *     portfolio from JWT. We keep them as separate routes (rather than a
         *     single 'report' that also returns the score) because the score
         *     endpoint is fast and the report endpoint is slow; users can poll
         *     the score frequently while the report takes seconds.
         */
        ReportFromActiveRequest: {
            /**
             * Risk Preference
             * @default 3
             */
            risk_preference?: number;
            /**
             * Risk Free Rate
             * @default 0.045
             */
            risk_free_rate?: number;
            /**
             * History Days
             * @default 365
             */
            history_days?: number;
            /**
             * Market Shock
             * @description Stress-test market move applied to the portfolio.
             * @default -0.1
             */
            market_shock?: number;
        };
        /**
         * RiskExplainInput
         * @description Compact deterministic summary the page already has. Every field is
         *     optional so the one endpoint serves both the Health Score page (score
         *     side) and the Risk Report page (report side).
         */
        RiskExplainInput: {
            /**
             * Source
             * @default score
             * @enum {string}
             */
            source?: "score" | "risk";
            /** Overall Score */
            overall_score?: number | null;
            /** Dimensions */
            dimensions?: {
                [key: string]: components["schemas"]["ExplainDimension"];
            };
            metrics?: components["schemas"]["ExplainMetrics"];
            /** Top Component Var */
            top_component_var?: components["schemas"]["ExplainContributor"][];
            /** Factor Betas */
            factor_betas?: {
                [key: string]: number;
            };
            /** Stress Loss */
            stress_loss?: number | null;
            /** Stress Market Shock */
            stress_market_shock?: number | null;
            /** Liquidity Outliers */
            liquidity_outliers?: components["schemas"]["ExplainLiquidity"][];
            snapshot_delta?: components["schemas"]["ExplainSnapshotDelta"] | null;
        };
        /**
         * ScoreFromActiveRequest
         * @description Body for ``POST /api/v1/risk/score_from_active``.
         *
         *     All fields optional — the endpoint resolves the active portfolio
         *     from the caller's JWT. ``risk_preference`` and ``risk_free_rate``
         *     override the defaults baked into the score for that one call.
         */
        ScoreFromActiveRequest: {
            /**
             * Risk Preference
             * @default 3
             */
            risk_preference?: number;
            /**
             * Risk Free Rate
             * @default 0.045
             */
            risk_free_rate?: number;
            /**
             * History Days
             * @description Trailing window of daily history used to build the returns matrix. 365 ≈ 252 trading days, the engine's preferred minimum. Cap at 10 years.
             * @default 365
             */
            history_days?: number;
        };
        /**
         * ScoreRequest
         * @description Body for ``POST /api/v1/risk/score``.
         *
         *     ``returns`` is an optional inline daily-returns matrix as a
         *     ``{ticker: [r1, r2, …]}`` dict. When omitted the endpoint synthesises
         *     a deterministic-but-realistic return stream so the API is testable
         *     without a market-data fetcher. Production callers should always pass
         *     real returns; the synthetic fallback is documented as a dev aid.
         */
        ScoreRequest: {
            /** Holdings */
            holdings: components["schemas"]["HoldingIn"][];
            /**
             * Risk Preference
             * @default 3
             */
            risk_preference?: number;
            /**
             * Risk Free Rate
             * @default 0.045
             */
            risk_free_rate?: number;
            /** Returns */
            returns?: {
                [key: string]: number[];
            } | null;
            /** Benchmark Returns */
            benchmark_returns?: number[] | null;
        };
        /**
         * SourceRef
         * @description Where one slice of the FactPack came from + how complete it was.
         */
        SourceRef: {
            /** Field */
            field: string;
            /** Source */
            source: string;
            /** As Of */
            as_of?: string | null;
            /**
             * Coverage
             * @default 0
             */
            coverage?: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValuationBlock */
        ValuationBlock: {
            /** Pe */
            pe?: number | null;
            /** Forward Pe */
            forward_pe?: number | null;
            /** Ps */
            ps?: number | null;
            /** Pb */
            pb?: number | null;
            /** Ev Ebitda */
            ev_ebitda?: number | null;
            /** Fcf Yield */
            fcf_yield?: number | null;
            /** Dividend Yield */
            dividend_yield?: number | null;
            /** Band */
            band?: string | null;
            /** Peer Median Pe */
            peer_median_pe?: number | null;
        };
        /** VerdictRequest */
        VerdictRequest: {
            /** Ticker */
            ticker?: string | null;
            /** @description The FactPack already fetched from GET /research/fact_pack/{ticker}. When supplied the verdict REUSES it (no second network fetch). */
            fact_pack?: components["schemas"]["FactPack"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    score_portfolio_endpoint_api_v1_risk_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_from_active_endpoint_api_v1_risk_score_from_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreFromActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    last_snapshot_endpoint_api_v1_risk_last_snapshot_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    snapshot_history_endpoint_api_v1_risk_snapshot_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    report_from_active_endpoint_api_v1_risk_report_from_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportFromActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    efficient_frontier_endpoint_api_v1_risk_efficient_frontier_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportFromActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scenarios_endpoint_api_v1_risk_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportFromActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_endpoint_api_v1_risk_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RiskExplainInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    benchmarks_endpoint_api_v1_risk_benchmarks_get: {
        parameters: {
            query?: {
                days?: number;
                risk_free?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    historical_scenarios_endpoint_api_v1_risk_historical_scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    var_backtest_endpoint_api_v1_risk_var_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_my_portfolios_api_v1_portfolios_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_portfolio_endpoint_api_v1_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_endpoint_api_v1_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_portfolio_endpoint_api_v1_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prices_api_v1_market_prices_get: {
        parameters: {
            query: {
                /** @description Comma-separated ticker list. Case-insensitive, deduped server-side. Example: `?tickers=SPY,BND,AAPL`. */
                tickers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    portfolio_sentiment_api_v1_market_sentiment_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_series_api_v1_macro_series_get: {
        parameters: {
            query: {
                /** @description Comma-separated FRED series IDs. Only allow-listed series are returned — see ``services.macro_data.ALLOWED_FRED_SERIES``. Example: `?series=DFF,CPIAUCSL,UNRATE`. */
                series: string;
                /** @description Trailing window in days. Min 30, max 10 years. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yield_curve_api_v1_macro_yield_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_regime_api_v1_macro_regime_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_regime_detail_endpoint_api_v1_macro_regime_detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_movers_endpoint_api_v1_macro_movers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_news_endpoint_api_v1_macro_news_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    billing_me_api_v1_billing_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    billing_admin_usage_api_v1_billing_admin_usage_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    billing_admin_metrics_api_v1_billing_admin_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    billing_admin_status_api_v1_billing_admin_status_get: {
        parameters: {
            query?: {
                live?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_checkout_session_endpoint_api_v1_billing_checkout_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckoutSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_portal_session_endpoint_api_v1_billing_portal_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortalSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilot_chat_endpoint_api_v1_copilot_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilot_ask_endpoint_api_v1_copilot_ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CopilotAskRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    copilot_chat_stream_endpoint_api_v1_copilot_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    backtest_active_endpoint_api_v1_quant_backtest_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BacktestRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    attribution_active_endpoint_api_v1_quant_attribution_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    fact_pack_api_v1_research_fact_pack__ticker__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticker: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verdict_api_v1_research_verdict_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerdictRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    smart_money_api_v1_institutions_smart_money_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    top_api_v1_institutions_top_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    detail_api_v1_institutions__cik__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cik: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_feedback_api_v1_feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
