/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness + import sanity
         * @description Return a coarse health snapshot.
         *
         *     Imports the load-bearing internal modules so a broken deploy
         *     (missing dep, broken import path, syntax error in a transitive)
         *     surfaces at ``/health`` instead of at the first real call.
         *     The imports are intentionally re-done per call rather than at
         *     module load — that way a hot patch + reload doesn't need a
         *     process restart to be visible here.
         */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score an explicit portfolio without touching Supabase
         * @description Compute deterministic 0-1000 score + 3 dimension scores + the
         *     raw risk metrics for the supplied holdings.
         *
         *     Deliberately stateless: no Supabase reads, no LLM calls, no
         *     cookie / JWT requirement. Same Pydantic + engine path used by
         *     the Streamlit Copilot page; the math is shared.
         */
        post: operations["score_portfolio_endpoint_api_v1_risk_score_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/score_from_active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Score the authed user's active portfolio using real market data
         * @description Compute the deterministic 0..1000 score for the caller's active
         *     portfolio, using real adjusted-close prices pulled (and cached)
         *     via the backend market-data service.
         *
         *     Resolution order for "active portfolio":
         *       1. The default portfolio flagged in Supabase (``is_default=true``).
         *       2. The most-recent portfolio if no default is set.
         *       3. Empty → 422 ``no_active_portfolio``.
         *
         *     Why not also let the caller pass a ``portfolio_id``? Phase 4 keeps
         *     the contract minimal — the UI shows one card per portfolio with a
         *     "Set as default" toggle. When a richer UI lands, we add an
         *     explicit ``portfolio_id`` field.
         */
        post: operations["score_from_active_endpoint_api_v1_risk_score_from_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risk/report_from_active": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Full risk report for the authed user's active portfolio
         * @description Build the full ``RiskReport`` (VaR/CVaR, factor betas, stress
         *     test, component VaR, liquidity) using real adjusted-close prices
         *     via the same cached service ``/risk/score_from_active`` uses.
         *
         *     Heavier than /score_from_active (Monte Carlo + factor regressions
         *     against SPY/QQQ/GLD/TLT/IWM/VTV — fetches their history too). The
         *     file-cached market_data layer absorbs the cold-cache latency.
         */
        post: operations["report_from_active_endpoint_api_v1_risk_report_from_active_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/equity/deep_analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run the single-name equity analyst (no LLM in Phase 1)
         * @description Return the deterministic ``DeepAnalysis`` placeholder for the
         *     requested ticker / dossier.
         *
         *     Phase 1 does NOT invoke the LLM: it returns the placeholder
         *     analysis (HOLD / low confidence) so the frontend can wire the
         *     dashboard before we plumb billing-aware LLM routing. The placeholder
         *     is the same one the equity module emits when its ``llm_callable``
         *     argument is None — see ``libs.analysis.equity_research``.
         */
        post: operations["deep_analysis_api_v1_equity_deep_analysis_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Return the authed user's portfolios
         * @description Authed-only. Returns the JWT holder's RLS-filtered portfolios.
         */
        get: operations["list_my_portfolios_api_v1_portfolios_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new portfolio owned by the caller
         * @description Insert a new row. Supabase RLS pins `user_id` to the caller via
         *     the `DEFAULT auth.uid()` clause on the column — we never send it
         *     explicitly, so a buggy client can't impersonate.
         */
        post: operations["create_portfolio_endpoint_api_v1_portfolios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portfolios/{portfolio_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete one portfolio owned by the caller
         * @description Hard delete. RLS prevents touching rows the caller doesn't own.
         */
        delete: operations["delete_portfolio_endpoint_api_v1_portfolios__portfolio_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update one or more fields on a portfolio
         * @description Patch fields. Only fields explicitly set in the request body are
         *     applied; omitted fields keep their existing DB values.
         */
        patch: operations["update_portfolio_endpoint_api_v1_portfolios__portfolio_id__patch"];
        trace?: never;
    };
    "/api/v1/market/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest adjusted close per ticker
         * @description Return the most recent adjusted close + bar date per ticker.
         *
         *     Tickers yfinance can't price (delisted, typo) are silently
         *     omitted from `prices`; compare against `requested` to find them.
         */
        get: operations["get_prices_api_v1_market_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Last N days of one or more FRED series
         * @description Return latest-value + trailing window for each allow-listed series.
         */
        get: operations["get_series_api_v1_macro_series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/macro/yield_curve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest US Treasury daily yield curve
         * @description Return today's (or the most recent published) Treasury curve.
         */
        get: operations["get_yield_curve_api_v1_macro_yield_curve_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DeepAnalysisRequest */
        DeepAnalysisRequest: {
            /** Ticker */
            ticker?: string | null;
            /**
             * Fmp Key
             * @description Pass-through FMP key for the dossier fetch. Optional.
             */
            fmp_key?: string | null;
            /**
             * Dossier Override
             * @description When supplied, the endpoint SKIPS the network dossier fetch and uses this dict verbatim. Lets tests + offline clients exercise the analysis without yfinance / FMP.
             */
            dossier_override?: {
                [key: string]: unknown;
            } | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HoldingIn
         * @description One row in the request body. Maps 1:1 to
         *     ``domain.models.AssetPositionInput`` minus a couple of nullable
         *     quality-of-life fields. Same validation rules apply once we
         *     rebuild the engine's model — keeping the schema deliberately
         *     permissive here lets the engine emit the precise error code.
         */
        HoldingIn: {
            /** Ticker */
            ticker: string;
            /**
             * Name
             * @default
             */
            name?: string;
            /**
             * Asset Type
             * @default public_security
             * @enum {string}
             */
            asset_type?: "public_security" | "cash" | "crypto" | "real_estate";
            /** Market Value */
            market_value: number;
            /**
             * Cost Basis
             * @default 0
             */
            cost_basis?: number;
            /**
             * Expense Ratio
             * @default 0
             */
            expense_ratio?: number;
            /**
             * Source
             * @default api
             */
            source?: string;
            /** Proxy Ticker */
            proxy_ticker?: string | null;
            /**
             * Enabled
             * @default true
             */
            enabled?: boolean;
        };
        /**
         * HoldingValue
         * @description One ticker's persisted record on a portfolio row.
         */
        HoldingValue: {
            /** Shares */
            shares: number;
            /** Avg Cost */
            avg_cost?: number | null;
            /** Sector */
            sector?: string | null;
            /** Asset Type */
            asset_type?: string | null;
            /** Account */
            account?: string | null;
            /** Currency */
            currency?: string | null;
            /** Margin Eligible */
            margin_eligible?: boolean | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * PortfolioCreateRequest
         * @description Body for ``POST /api/v1/portfolios``.
         */
        PortfolioCreateRequest: {
            /** Name */
            name: string;
            /** Holdings */
            holdings?: {
                [key: string]: components["schemas"]["HoldingValue"];
            };
            /**
             * Margin Loan
             * @default 0
             */
            margin_loan?: number;
            /**
             * Contributed Capital
             * @default 0
             */
            contributed_capital?: number;
            /**
             * Cash Balance
             * @default 0
             */
            cash_balance?: number;
            /**
             * Is Default
             * @default false
             */
            is_default?: boolean;
        };
        /**
         * PortfolioPatchRequest
         * @description Body for ``PATCH /api/v1/portfolios/{id}``.
         *
         *     Every field is optional — the route only applies fields the caller
         *     explicitly set so a small UI edit doesn't accidentally null other
         *     columns.
         */
        PortfolioPatchRequest: {
            /** Name */
            name?: string | null;
            /** Holdings */
            holdings?: {
                [key: string]: components["schemas"]["HoldingValue"];
            } | null;
            /** Margin Loan */
            margin_loan?: number | null;
            /** Contributed Capital */
            contributed_capital?: number | null;
            /** Cash Balance */
            cash_balance?: number | null;
            /** Is Default */
            is_default?: boolean | null;
        };
        /**
         * ReportFromActiveRequest
         * @description Body for ``POST /api/v1/risk/report_from_active``.
         *
         *     Matches ScoreFromActiveRequest — both endpoints resolve the active
         *     portfolio from JWT. We keep them as separate routes (rather than a
         *     single 'report' that also returns the score) because the score
         *     endpoint is fast and the report endpoint is slow; users can poll
         *     the score frequently while the report takes seconds.
         */
        ReportFromActiveRequest: {
            /**
             * Risk Preference
             * @default 3
             */
            risk_preference?: number;
            /**
             * Risk Free Rate
             * @default 0.045
             */
            risk_free_rate?: number;
            /**
             * History Days
             * @default 730
             */
            history_days?: number;
            /**
             * Market Shock
             * @description Stress-test market move applied to the portfolio.
             * @default -0.1
             */
            market_shock?: number;
        };
        /**
         * ScoreFromActiveRequest
         * @description Body for ``POST /api/v1/risk/score_from_active``.
         *
         *     All fields optional — the endpoint resolves the active portfolio
         *     from the caller's JWT. ``risk_preference`` and ``risk_free_rate``
         *     override the defaults baked into the score for that one call.
         */
        ScoreFromActiveRequest: {
            /**
             * Risk Preference
             * @default 3
             */
            risk_preference?: number;
            /**
             * Risk Free Rate
             * @default 0.045
             */
            risk_free_rate?: number;
            /**
             * History Days
             * @description Trailing window of daily history used to build the returns matrix. 365 ≈ 252 trading days, the engine's preferred minimum. Cap at 10 years.
             * @default 365
             */
            history_days?: number;
        };
        /**
         * ScoreRequest
         * @description Body for ``POST /api/v1/risk/score``.
         *
         *     ``returns`` is an optional inline daily-returns matrix as a
         *     ``{ticker: [r1, r2, …]}`` dict. When omitted the endpoint synthesises
         *     a deterministic-but-realistic return stream so the API is testable
         *     without a market-data fetcher. Production callers should always pass
         *     real returns; the synthetic fallback is documented as a dev aid.
         */
        ScoreRequest: {
            /** Holdings */
            holdings: components["schemas"]["HoldingIn"][];
            /**
             * Risk Preference
             * @default 3
             */
            risk_preference?: number;
            /**
             * Risk Free Rate
             * @default 0.045
             */
            risk_free_rate?: number;
            /** Returns */
            returns?: {
                [key: string]: number[];
            } | null;
            /** Benchmark Returns */
            benchmark_returns?: number[] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    score_portfolio_endpoint_api_v1_risk_score_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    score_from_active_endpoint_api_v1_risk_score_from_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScoreFromActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_from_active_endpoint_api_v1_risk_report_from_active_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportFromActiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deep_analysis_api_v1_equity_deep_analysis_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeepAnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_portfolios_api_v1_portfolios_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    create_portfolio_endpoint_api_v1_portfolios_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_portfolio_endpoint_api_v1_portfolios__portfolio_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_portfolio_endpoint_api_v1_portfolios__portfolio_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                portfolio_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PortfolioPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_prices_api_v1_market_prices_get: {
        parameters: {
            query: {
                /** @description Comma-separated ticker list. Case-insensitive, deduped server-side. Example: `?tickers=SPY,BND,AAPL`. */
                tickers: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_v1_macro_series_get: {
        parameters: {
            query: {
                /** @description Comma-separated FRED series IDs. Only allow-listed series are returned — see ``services.macro_data.ALLOWED_FRED_SERIES``. Example: `?series=DFF,CPIAUCSL,UNRATE`. */
                series: string;
                /** @description Trailing window in days. Min 30, max 10 years. */
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_yield_curve_api_v1_macro_yield_curve_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
